version: "3.9"
services:
  web:
    build:
      context: ../client
      args: # These URLs must not be quoted.
        - VITE_API_ADDRESS=http://backend:8090
        - VITE_PUBLIC_API_ADDRESS=http://localhost:7001
    ports:
      - "7000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ../server
    ports:
      - "7001:8090"
    volumes:
      - "./pb_data:/pb_data:rw"