version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - platform
      - platform-api
  platform:
    image: ghcr.io/goatcorp/plugin-platform-client:latest
    ports:
      - "7000:3000"
    depends_on:
      - platform-api
  platform-api:
    image: ghcr.io/goatcorp/plugin-platform-server:latest
    ports:
      - "7001:8090"
    volumes:
      - "pb_data:/pb_data:rw"
  watchtower:
    image: containrrr/watchtower
    environment:
      WATCHTOWER_ROLLING_RESTART: "true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${HOME}/.docker/config.json:/config.json:ro"
    command: --interval 30
volumes:
  pb_data: